apiVersion: v1
kind: Pod
metadata:
  name: mig-gpu-pod
  labels:
    app: mig-training
spec:
  containers:
  - name: training-container
    image: nvcr.io/nvidia/pytorch:25.09-py3
    command: ["python", "train.py"]
    resources:
      requests:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/mig-2g.45gb: "2"  # Request 2 MIG slices of 2g.45gb each
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/mig-2g.45gb: "2"
    env:
    - name: CUDA_VISIBLE_DEVICES
      value: "0,1"  # This will be automatically set by the device plugin
    volumeMounts:
    - name: data-volume
      mountPath: /data
      readOnly: true
    - name: output-volume
      mountPath: /output
  volumes:
  - name: data-volume
    hostPath:
      path: /data/dataset
      type: Directory
  - name: output-volume
    hostPath:
      path: /output
      type: Directory
  restartPolicy: Never
  # Optional: Use node selector to target MIG-enabled nodes
  nodeSelector:
    mig-enabled: "true"
